region = "us-central1"
gcp_project = "cloudglobaldelivery-1000135575"
credentials= "credentials.json"
sonarvpc = "default"
sonarsub = "default"
// elk_instance_name = "elk"
harbor_instance_name = "harbor"
